---
- name: Настройка сетевого интерфейса
  hosts: myhosts
  become: true
  vars:
    interface: "enp0s8"
    netplan_cfg: "/etc/netplan/50-cloud-init.yaml"

  tasks:
    - name: 1. Включение интерфейса
      ansible.builtin.command: "ip link set {{ interface }} up"
      changed_when: false

    - name: 2. Прописан ли интерфейс в файле Netplan?
      ansible.builtin.command: "grep -q '{{ interface }}:' {{ netplan_cfg }}"
      register: interface_check
      failed_when: false
      changed_when: false

    - name: 3. Добавление конфигурации интерфейса в Netplan
      ansible.builtin.blockinfile:
        path: "{{ netplan_cfg }}"
        insertafter: "ethernets:"
        marker: >
          {{ ' # {mark} ANSIBLE MANAGED BLOCK FOR '
          | indent(4, true) }}{{ interface }}
        block: |
          {{ interface | indent(4, true) }}:
          {{ 'dhcp4: true' | indent(6, true) }}
      when: interface_check.rc != 0
      # Если блок добавился, мы уведомляем обработчик цепочки настроек сети:
      notify: Setup Netplan Interface

    - name: 7. Обновление пакетов (apt update & upgrade)
      ansible.builtin.apt:
        update_cache: true  # apt update
        upgrade: dist  # apt upgrade
        cache_valid_time: 3600  # кэш обновлялся в течение часа

  handlers:
    # Этот обработчик запускает всю цепочку тасок, если Netplan изменился
    - name: Setup Netplan Interface
      ansible.builtin.command: "netplan apply"
      changed_when: true
      notify:
        - Wait for IP
        - Check Ping

    - name: Wait for IP
      ansible.builtin.pause:
        seconds: 10
      notify: Check Ping

    - name: Check Ping
      ansible.builtin.command: "ping -c 4 77.88.8.8"
      changed_when: false  # Пинг просто проверяет сеть, он ничего не изменяет
