---
- name: Установка Nginx
  hosts: myhosts
  become: true

  tasks:
    - name: Установка Nginx
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: true  # apt update
        cache_valid_time: 3600

    - name: Запуск добавление в автозагрузку
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Проверка
      ansible.builtin.uri:
        url: "http://localhost"
        status_code: 200
      register: http_check

    - name: Статус службы Nginx
      ansible.builtin.systemd:
        name: nginx
      register: nginx_status

    - name: Вывод статуса Nginx в консоль
      ansible.builtin.debug:
        msg:
          - >
            HTTP Статус:
            {{ http_check.status }}
          - >
            Служба Nginx:
            {{ nginx_status.status.ActiveState }}
            ({{ nginx_status.status.SubState }})
